# SonarQube server settings
sonar.host.url=http://localhost:9000
sonar.token=squ_f57fcc9e0bf567cc9112e394cace81ec485ac2be

# Project identification
sonar.projectKey=econ
sonar.projectName=econ
sonar.projectVersion=1.0

# Project sources
sonar.sources=controllers,helpers,middlewares,client/src/pages,client/src/context,models

# Location of test files (following Suggested Testing Scope)
sonar.tests=controllers,helpers,middlewares,client/src/pages,client/src/context

# Test files
sonar.test.inclusions=**/*.test.js

# Files to be treated as not-source files
sonar.exclusions=**/*.test.js,controllers/_tests_/**/*.js

# Files to be excluded from coverage
sonar.coverage.exclusions=client/src/pages/*.js

# Location of coverage report paths
sonar.javascript.lcov.reportPaths=coverage/lcov.info