# SonarQube server settings
sonar.host.url=http://localhost:9000
sonar.token=squ_f57fcc9e0bf567cc9112e394cace81ec485ac2be

# Project identification
sonar.projectKey=econ
sonar.projectName=econ
sonar.projectVersion=1.0

# Analysis settings
sonar.sources=client
